hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

spring:
  jpa:
    hibernate:
      ddl-auto: update
  dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dbCreate: update
    url: jdbc:h2:./developmentDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
